# Generated by Django 3.2.3 on 2021-08-26 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_posted',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='discription',
        ),
    ]
