# Generated by Django 3.2.3 on 2021-08-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='pic.jpg', upload_to='profile_pics'),
        ),
    ]
